# flutter:
#   assets:
    # - assets/images/onboarding1.png
    # - assets/images/onboarding2.png
    # - assets/images/onboarding3.png
    # - assets/images/profile_picture.png
    # - assets/images/service2.png
    # - assets/images/service3.png
    # - assets/images/service4.png
    # - assets/images/service5.png
    # - assets/images/service6.png
    # - assets/images/onboarding3_b.png
    # - assets/images/google_logo.png
    # - assets/images/sarab.png
    # - assets/images/sfr.png
    # - assets/images/sen.png
    # - assets/images/face_shape.png
    # - assets/images/id_things.png
